// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Context;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FKCenterId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId");

                    b.HasIndex("FKCenterId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.ChildrenProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FKAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileId");

                    b.HasIndex("FKAccountId");

                    b.ToTable("ChildrenProfiles");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufacturerId"));

                    b.Property<string>("ActiveStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FKFeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FKProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("FKFeedbackId");

                    b.HasIndex("FKProfileId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.OrderPackageDetail", b =>
                {
                    b.Property<Guid>("OrderPackageDetaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FKOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FKVaccinePackageId")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.Property<int>("VaccinePackageId")
                        .HasColumnType("int");

                    b.HasKey("OrderPackageDetaiId");

                    b.HasIndex("OrderId");

                    b.HasIndex("VaccinePackageId");

                    b.ToTable("OrderPackageDetails");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.OrderVaccineDetail", b =>
                {
                    b.Property<Guid>("OrderVaccineDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FKOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FKVaccineId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("OrderVaccineDetailId");

                    b.HasIndex("FKOrderId");

                    b.HasIndex("FKVaccineId");

                    b.ToTable("OrderVaccineDetails");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<Guid>("FKOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PayAmount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("FKOrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.VaccinationSchedule", b =>
                {
                    b.Property<Guid>("VaccinationScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActualDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdministeredBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoseNumber")
                        .HasColumnType("int");

                    b.Property<int>("FKCenterId")
                        .HasColumnType("int");

                    b.Property<Guid>("FKOrderPackageDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FKOrderVaccineDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FKProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("VaccinationScheduleId");

                    b.HasIndex("FKCenterId");

                    b.HasIndex("FKOrderPackageDetailsId");

                    b.HasIndex("FKOrderVaccineDetailsId");

                    b.HasIndex("FKProfileId");

                    b.ToTable("VaccinationSchedules");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.Vaccine", b =>
                {
                    b.Property<int>("VaccineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccineId"));

                    b.Property<DateTime>("BetweenPeriod")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FKBatchId")
                        .HasColumnType("int");

                    b.Property<int>("FKCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("IngredientsDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<int>("UnitOfVolume")
                        .HasColumnType("int");

                    b.HasKey("VaccineId");

                    b.HasIndex("FKBatchId");

                    b.HasIndex("FKCategoryId");

                    b.ToTable("Vaccines");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.VaccineBatch", b =>
                {
                    b.Property<int>("VaccineBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccineBatchId"));

                    b.Property<string>("ActiveStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FKCenterId")
                        .HasColumnType("int");

                    b.Property<int>("FKManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("VaccineBatchId");

                    b.HasIndex("FKCenterId");

                    b.HasIndex("FKManufacturerId");

                    b.ToTable("VaccineBatches");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.VaccineCategory", b =>
                {
                    b.Property<int>("VaccineCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccineCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FKParentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaccineCategoryId");

                    b.HasIndex("FKParentCategoryId");

                    b.ToTable("VaccineCategories");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.VaccineCenter", b =>
                {
                    b.Property<int>("VacineCenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VacineCenterId"));

                    b.Property<int>("ContactNumber")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VacineCenterId");

                    b.ToTable("VaccineCenters");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.VaccineHistory", b =>
                {
                    b.Property<Guid>("VacineHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdministeredBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AdministeredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentationProvided")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FKAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FKCenterId")
                        .HasColumnType("int");

                    b.Property<Guid>("FKProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FKVaccineId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VerifiedStatus")
                        .HasColumnType("int");

                    b.HasKey("VacineHistoryId");

                    b.HasIndex("FKAccountId");

                    b.HasIndex("FKCenterId");

                    b.HasIndex("FKProfileId");

                    b.HasIndex("FKVaccineId");

                    b.ToTable("VaccineHistories");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.VaccinePackage", b =>
                {
                    b.Property<int>("VaccinePackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccinePackageId"));

                    b.Property<string>("PackageDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageStatus")
                        .HasColumnType("int");

                    b.HasKey("VaccinePackageId");

                    b.ToTable("VaccinePackages");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.VaccinePackageDetail", b =>
                {
                    b.Property<Guid>("VaccinePackageDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FKVaccineId")
                        .HasColumnType("int");

                    b.Property<int>("FKVaccinePackageId")
                        .HasColumnType("int");

                    b.Property<int>("PackagePrice")
                        .HasColumnType("int");

                    b.HasKey("VaccinePackageDetailId");

                    b.HasIndex("FKVaccineId");

                    b.HasIndex("FKVaccinePackageId");

                    b.ToTable("VaccinePackageDetails");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.VaccineReaction", b =>
                {
                    b.Property<Guid>("VaccineReactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FKVaccineScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReactionTime")
                        .HasColumnType("int");

                    b.Property<int>("ResolvedTime")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("VaccineReactionId");

                    b.HasIndex("FKVaccineScheduleId");

                    b.ToTable("VaccineReactions");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.Account", b =>
                {
                    b.HasOne("PRN222_Group_Project.Models.Entities.VaccineCenter", "Center")
                        .WithMany()
                        .HasForeignKey("FKCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Center");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.ChildrenProfile", b =>
                {
                    b.HasOne("PRN222_Group_Project.Models.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("FKAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.Order", b =>
                {
                    b.HasOne("PRN222_Group_Project.Models.Entities.Feedback", "Feedback")
                        .WithMany()
                        .HasForeignKey("FKFeedbackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN222_Group_Project.Models.Entities.ChildrenProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("FKProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feedback");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.OrderPackageDetail", b =>
                {
                    b.HasOne("PRN222_Group_Project.Models.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN222_Group_Project.Models.Entities.VaccinePackage", "VaccinePackage")
                        .WithMany()
                        .HasForeignKey("VaccinePackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("VaccinePackage");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.OrderVaccineDetail", b =>
                {
                    b.HasOne("PRN222_Group_Project.Models.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("FKOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN222_Group_Project.Models.Entities.Vaccine", "Vaccine")
                        .WithMany()
                        .HasForeignKey("FKVaccineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.Payment", b =>
                {
                    b.HasOne("PRN222_Group_Project.Models.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("FKOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.VaccinationSchedule", b =>
                {
                    b.HasOne("PRN222_Group_Project.Models.Entities.VaccineCenter", "Center")
                        .WithMany()
                        .HasForeignKey("FKCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN222_Group_Project.Models.Entities.OrderPackageDetail", "OrderPackageDetail")
                        .WithMany()
                        .HasForeignKey("FKOrderPackageDetailsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN222_Group_Project.Models.Entities.OrderVaccineDetail", "OrderVaccineDetail")
                        .WithMany()
                        .HasForeignKey("FKOrderVaccineDetailsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN222_Group_Project.Models.Entities.ChildrenProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("FKProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("OrderPackageDetail");

                    b.Navigation("OrderVaccineDetail");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.Vaccine", b =>
                {
                    b.HasOne("PRN222_Group_Project.Models.Entities.VaccineBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("FKBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN222_Group_Project.Models.Entities.VaccineCategory", "Category")
                        .WithMany()
                        .HasForeignKey("FKCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.VaccineBatch", b =>
                {
                    b.HasOne("PRN222_Group_Project.Models.Entities.VaccineCenter", "Center")
                        .WithMany()
                        .HasForeignKey("FKCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN222_Group_Project.Models.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("FKManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.VaccineCategory", b =>
                {
                    b.HasOne("PRN222_Group_Project.Models.Entities.VaccineCategory", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("FKParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.VaccineHistory", b =>
                {
                    b.HasOne("PRN222_Group_Project.Models.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("FKAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN222_Group_Project.Models.Entities.VaccineCenter", "Center")
                        .WithMany()
                        .HasForeignKey("FKCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN222_Group_Project.Models.Entities.ChildrenProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("FKProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN222_Group_Project.Models.Entities.Vaccine", "Vaccine")
                        .WithMany()
                        .HasForeignKey("FKVaccineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Center");

                    b.Navigation("Profile");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.VaccinePackageDetail", b =>
                {
                    b.HasOne("PRN222_Group_Project.Models.Entities.Vaccine", "Vaccine")
                        .WithMany()
                        .HasForeignKey("FKVaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN222_Group_Project.Models.Entities.VaccinePackage", "VaccinePackage")
                        .WithMany()
                        .HasForeignKey("FKVaccinePackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaccine");

                    b.Navigation("VaccinePackage");
                });

            modelBuilder.Entity("PRN222_Group_Project.Models.Entities.VaccineReaction", b =>
                {
                    b.HasOne("PRN222_Group_Project.Models.Entities.VaccinationSchedule", "VaccineSchedule")
                        .WithMany()
                        .HasForeignKey("FKVaccineScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaccineSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
